### PR TITLE
Fix #98: Register listeners once to prevent scope being retained

### LINKED ISSUE #98: Memory leak by not clearing $rootScope.$on('$viewContentLoaded') listener
Hi,

There are 2 or 3 places that use ````$rootScope.$on('$viewContentLoaded')````, wihout actually clearing the listener in scope destroy method. I had a test only for  ````$rootScope.$on('$viewContentLoaded', function () { renderBreadcrumb();});````. Because the rootScope is never destroyed, it keeps it's renderBreadcrumb listener, having some scopes as context variables. So navigating through multiple views, on rootScope such listeners would add and the scopes that we use for the components, together with their data and elements, will remain stuck with those closures.

For the moment I had just a test like 
````var unregister = $rootScope.$on('$viewContentLoaded', function () {  renderBreadcrumb(); });````

````function handleDestroyEvent() { unregister(); } ````

```` scope.$on("$destroy",handleDestroyEvent); ````

Checking the heap with Chrome profiling, it seems to release the scopes.

### PR DESCRIPTION
**Pull request by ronaldheft**
Fixes #98. A more in depth refactor of how the listener are registered is probably a preferred solution, but this fixes the core issue leading to the memory leak. More details to be posted in #98.

Note: Angular 1.5 build was failing prior to me working on this PR. I did not resolve the issues with Angular 1.5.

### CODE REVIEW

**Comment by ncuillery** [comment]
Hi,

It sounds pretty good ! Thanks for the PR.

I'll fix the tests soon.

**Comment by ncuillery** [comment]
Hi, can you rebase your PR please ? Tests should be working.

**Comment by ronaldheft** [comment]
Sure, rebased. 😄

**Comment by ncuillery** [comment]
Landed thanks! I'll wait few days before releasing a new version (others PR are coming).

**Pull request merged**
