### PR TITLE
feat(ncyBreadcrumbLast): add custom templating

### LINKED ISSUE #123: No way to customize ncy-breadcrumb-last
I noticed this when attempting to enable a custom template that binds html, like the example in the documentation. When using the `ncy-breadcrumb-last` directive, the label shows all of the escaped markup because the directive is hard-coded to use `'{{ncyBreadcrumbLabel}}'` (https://github.com/ncuillery/angular-breadcrumb/blob/master/src/angular-breadcrumb.js#L242). This greatly limits the ability to use both `ncy-breadcrumb-last` and custom templates together.

### LINKED ISSUE #125: Translating angular breadcrumb last
I understand that the ncy-breadcrumb can be translated using angular translate with custom template. However, I could not find a way to translate ncy-breadcrumb-last from the documentation.

`<span ncy-breadcrumb-last></span>`

### PR DESCRIPTION
**Pull request by freethejazz**
Add ability to set a custom `template` or `templateUrl` for
`ncyBreadCrumbLast`. Before, if a custom template that allowed HTML via
`ngBindHtml`, breadcrumb last would not behave properly since it escaped
HTML by default. A value could be assigned to the `ncyBreadcrumbLast`
directive to customize the template, but it would have to be done on
each instance of the directive used. Now, a template can be set once via
the `templateLast` and `templateLastUrl` properties of the configuration
object passed to `$breadcrumbProvider.setOptions`.

A few things to point out:

1. `ncyBreadcrumb` replaces the element the directive is set to, but `ncyBreadcrumbLast` does not. This means that the custom template that a user sets for `ncyBreadcrumbLast` will be wrapped by whatever element they added the directive to. This shouldn't be a huge problem, as it's the expected behavior today when assigning a custom value to `ncyBreadcrumbLast`.

2. I cringed a bit at just copying the two existing methods for `getTemplateLast` and `getTemplateLastUrl`, but I think it's probably the best way to go. I thought the added complexity of refactoring those functions for reusability was not worth it, considering they probably won't be used anywhere else. If you want those to be DRYer, let me know and I can do that.

3. I'm not married to any of the identifier names introduced here, so if any of them are displeasing let me know of your desired alternative and I'll change it.

3. In order to pass all the tests, I had to lock the `testLatest` version of angular to 1.4.9, instead of using the actual latest of 1.5.0. This is due to the fact that angular 1.5.0 causes tests to fail in master.

4. This functionality should be documented once it makes it's way into master.

Closes #123, Closes #125

### CODE REVIEW

**Comment by freethejazz** [comment]
Regarding # 4 above, I did not commit the version lock to the Grunfile, so integration tests will likely fail on the `testLatest` run.

**Comment by freethejazz** [comment]
I've opened a new issue (#135) to address the problem in the above comment

**Comment by ncuillery** [comment]
Thanks for this well-tested / well-explained PR. I sounds good to me.

We'll fix CI soon and then merge this one.

**Comment by ncuillery** [comment]
Hi, can you rebase your PR please ? Tests should be working.

**Comment by freethejazz** [comment]
Rebased and pushed! Tests worked locally, so I think we might be in the clear.

**Comment by ncuillery** [comment]
Landed, thanks !

I wait few days if recent PR are rebased by their authors, then I release a new version (will be the 0.5.0)

**Pull request merged**
