### PR TITLE
feat(addStateInChain) : Add showAbstract to ncyBreadcrumb options

### PR DESCRIPTION
**Pull request by KodeShark**
Give ability to show specific abstract states, even if options.includeAbstract is turned off in configuration

### CODE REVIEW

**Comment by ncuillery** [comment]
Hi,

Thank for the PR, clean, tested and I like your way of writing conditions. 

I have 2 comments:
- How about `force` instead of `showAbstract` ? I will be consistent with the existing skip option.
- I would like to have a test case with both skip & force option set to true (The result doesn't really matter, I just need to write what's happen in this case in the docs).

Can you do this ?

**Comment by KodeShark** [comment]
Sure. I actually had it set to force initially, but thought it may be too vague to the end user.

**Comment by ncuillery** [comment]
Merged, thanks @KodeShark !

**Comment by epelc** [comment]
@ncuillery Was this not released? I can't seem to find it in `0.3.3`.

**Comment by samzhao** [comment]
@epelc for now I think you'll have to use what's on master `bower install --save angular-breadcrumb#master`

**Pull request merged**
